
main:
	g++ Circulo.cpp ../glad.c -lglfw -ldl -o Circulo.out
	g++ Octagono.cpp ../glad.c -lglfw -ldl -o Octagono.out
	g++ Pentagono.cpp ../glad.c -lglfw -ldl -o Pentagono.out
	g++ Estrela.cpp ../glad.c -lglfw -ldl -o Estrela.out
	g++ Pizza.cpp ../glad.c -lglfw -ldl -o Pizza.out
	g++ Pacman.cpp ../glad.c -lglfw -ldl -o Pacman.out
